version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - err113
    - errorlint
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - godot
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - nakedret
    - nlreturn
    - noctx
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 100
      statements: 40
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - dupImport
        - unnecessaryBlock
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 10
    govet:
      disable:
        - fieldalignment
      enable-all: true
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
          - paralleltest
        path: tests
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
